version: "3.8"

services:
  app:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - .:/code
      - /data/desi:/data/desi
    command: bash -c "uvicorn main:app --reload --port 8089 --host 0.0.0.0"